[platformio]
boards_dir= ./boards

[env]
platform = espressif32@6.3.0
upload_protocol = esptool
framework = arduino

upload_speed = 921600
monitor_speed = 115200

[env:t5-4-7]
board = lilygo-t5-47
build_flags = -D CORE_DEBUG_LEVEL=3